# Gitleaks Configuration for TheTally
# This configuration allows legitimate environment variable patterns while detecting actual hardcoded secrets

[allowlist]
description = "Allow legitimate environment variable and configuration patterns"
regexes = [
  # Python environment variable patterns
  "os\\.getenv\\(",
  "os\\.environ\\[",
  "os\\.environ\\.get\\(",
  
  # Shell environment variable patterns
  "\\$\\{.*:-",
  "=\\$\\{.*:-",
  "DATABASE_PASSWORD=\\$\\{DATABASE_PASSWORD",
  "password=\\$\\{.*:-",
  
  # Echo statements for configuration
  "echo.*export.*PASSWORD",
  "echo.*PASSWORD.*=",
  "echo.*export.*DATABASE",
  
  # Docker environment patterns
  "POSTGRES_PASSWORD:",
  "MYSQL_PASSWORD:",
  "DATABASE_PASSWORD:",
  
  # Test data patterns
  "password.*=.*\"test",
  "password.*=.*\"example",
  "password.*=.*\"wrong",
  "password.*=.*\"Wrong",
  
  # Documentation examples
  "password.*=.*\"your-",
  "password.*=.*\"secure_",
  "password.*=.*\"dev_",
  
  # Generated password patterns
  "openssl rand -base64",
  "\\$\\{.*\\$\\(",
]

[[allowlist.paths]]
description = "Allow specific file patterns that contain legitimate examples"
regexes = [
  ".*\\.example$",
  ".*\\.env\\.example$",
  ".*test.*\\.py$",
  ".*tests/.*",
  ".*docs/.*",
  ".*README.*",
  ".*CONTRIBUTING.*",
  ".*troubleshooting/.*",
]

[[allowlist.commits]]
description = "Allow specific commit patterns if needed"
regexes = [
  ".*nosec.*",
  ".*example.*",
  ".*test.*",
]

# Custom rules for our specific patterns
[[rules]]
description = "Custom rule for environment variable assignments"
regex = '''password\s*=\s*["']?[^"']*["']?'''
entropy = 0
tags = ["custom", "environment"]

[[rules]]
description = "Custom rule for API key assignments"
regex = '''api_key\s*=\s*["']?[^"']*["']?'''
entropy = 0
tags = ["custom", "api"]

[[rules]]
description = "Custom rule for secret assignments"
regex = '''secret\s*=\s*["']?[^"']*["']?'''
entropy = 0
tags = ["custom", "secret"]
