# Gitleaks Configuration for TheTally
# This configuration allows legitimate environment variable patterns while detecting actual hardcoded secrets

[allowlist]
description = "Allow legitimate environment variable and configuration patterns"
regexes = [
  # Python environment variable patterns
  "os\\.getenv\\(",
  "os\\.environ\\[",
  "os\\.environ\\.get\\(",
  
  # Shell environment variable patterns
  "\\$\\{.*:-",
  "=\\$\\{.*:-",
  "DATABASE_PASSWORD=\\$\\{DATABASE_PASSWORD",
  "password=\\$\\{.*:-",
  
  # Echo statements for configuration
  "echo.*export.*PASSWORD",
  "echo.*PASSWORD.*=",
  "echo.*export.*DATABASE",
  
  # Docker environment patterns
  "POSTGRES_PASSWORD:",
  "MYSQL_PASSWORD:",
  "DATABASE_PASSWORD:",
  
  # Test data patterns
  "password.*=.*\"test",
  "password.*=.*\"example",
  "password.*=.*\"wrong",
  "password.*=.*\"Wrong",
  
  # Documentation examples
  "password.*=.*\"your-",
  "password.*=.*\"secure_",
  "password.*=.*\"dev_",
  
  # Generated password patterns
  "openssl rand -base64",
  "\\$\\{.*\\$\\(",
]

# Allow specific file patterns that contain legitimate examples
[allowlist.paths]
regexes = [
  ".*\\.example$",
  ".*\\.env\\.example$",
  ".*test.*\\.py$",
  ".*tests/.*",
  ".*docs/.*",
  ".*README.*",
  ".*CONTRIBUTING.*",
  ".*troubleshooting/.*",
]

# Allow specific commit patterns if needed
[allowlist.commits]
regexes = [
  ".*nosec.*",
  ".*example.*",
  ".*test.*",
]
