version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15
    container_name: thetally-db-dev
    environment:
      POSTGRES_DB: thetally_dev
      POSTGRES_USER: thetally_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thetally_user -d thetally_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend (Development)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: thetally-backend-dev
    environment:
      - DATABASE_URL=postgresql://thetally_user:password@database:5432/thetally_dev
      - DEBUG=true
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: thetally-frontend-dev
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

volumes:
  postgres_dev_data:
