version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15
    container_name: thetally-db
    environment:
      POSTGRES_DB: thetally_dev
      POSTGRES_USER: thetally_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thetally_user -d thetally_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build: ./backend
    container_name: thetally-backend
    environment:
      - DATABASE_URL=postgresql://thetally_user:password@database:5432/thetally_dev
      - DEBUG=true
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build: ./frontend
    container_name: thetally-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
