name: Feature Request
description: Request a new feature for TheTally
title: "[FEATURE] "
labels: ["enhancement", "feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Please describe the feature you'd like to see implemented.
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature in detail
      placeholder: What would you like to see implemented?
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature be used?
      placeholder: Describe the use case for this feature
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What needs to be done to consider this feature complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the feature request
      placeholder: Add any other context or screenshots about the feature request here
