# Production Environment Configuration
# This file contains production-specific settings that override defaults

# Application Settings
app:
  name: "TheTally"
  version: "1.0.0"
  debug: false
  environment: "production"

# API Configuration
api:
  host: "${API_HOST}"  # Must be set via environment variable
  port: "${API_PORT}"  # Must be set via environment variable
  cors_origins:
    - "${FRONTEND_URL}"  # Must be set via environment variable

# Database Configuration
database:
  url: "${DATABASE_URL}"  # Must be set via environment variable
  host: "${DATABASE_HOST}"
  port: "${DATABASE_PORT}"
  name: "${DATABASE_NAME}"
  user: "${DATABASE_USER}"
  password: "${DATABASE_PASSWORD}"
  pool_size: 20
  max_overflow: 30
  pool_timeout: 30
  pool_recycle: 3600

# GCP Database Configuration (for production)
gcp:
  project_id: "${GCP_PROJECT_ID}"
  region: "${GCP_REGION}"
  database_instance: "${GCP_DATABASE_INSTANCE}"
  database_version: "POSTGRES_15"
  database_tier: "db-n1-standard-1"  # Production tier
  database_ssl_mode: "require"

# Security Configuration
security:
  secret_key: "${SECRET_KEY}"  # Must be set via environment variable
  jwt_secret: "${JWT_SECRET}"  # Must be set via environment variable
  jwt_algorithm: "HS256"
  jwt_access_token_expire_minutes: 15
  jwt_refresh_token_expire_days: 7
  otp_issuer: "TheTally"
  otp_secret_length: 32

# File Upload Configuration
file_upload:
  max_file_size: 10485760  # 10MB
  allowed_file_types: ["csv", "ofx", "qif"]

# Logging Configuration
logging:
  level: "INFO"
  format: "json"
  include_audit_logs: true
  include_functional_logs: true
  include_debug_logs: false  # Disable debug logs in production

# Monitoring Configuration
monitoring:
  enable_metrics: true
  enable_health_checks: true
  enable_performance_monitoring: true

# Security Headers
security_headers:
  strict_transport_security: true
  content_security_policy: "default-src 'self'"
  x_frame_options: "DENY"
  x_content_type_options: "nosniff"
  referrer_policy: "strict-origin-when-cross-origin"